In [2]:
import pandas as pd

In [6]:
fpath = "../../scrna_processing/fastq_paths.txt"
df = pd.read_csv(fpath)
df.head()

   sample_id                                          file_path
0  Run4x0314  /nfs/turbo/umms-indikar/shared/projects/HSC/da...
1  Run3x0314  /nfs/turbo/umms-indikar/shared/projects/HSC/da...
2  Run1x0312  /nfs/turbo/umms-indikar/shared/projects/HSC/da...
3  Run6x0426  /nfs/turbo/umms-indikar/shared/projects/HSC/da...
4  Run1x0415  /nfs/turbo/umms-indikar/shared/projects/HSC/da...

In [10]:
run_basecaller_map = {
    "Run1x0312": "fast_v4.2.0",
    "Run6x0426": "hac_v3.3",
    "Run1x0415": "hac_v3.3",
    "Run5x0314": "fast_v4.2.0",
    "Run6x0314": "fast_v4.2.0",
    "Run7x0426": "hac_v3.3",
    "Run2x0313": "fast_v4.2.0",
    "Run7x0315": "hac_v4.2.0",
    "Run2x0416": "hac_v3.3",
    "Run8x0426": "fast_v3.4",
    "Run4x0314": "fast_v4.2.0",
    "Run3x0314": "fast_v4.2.0",
    "Run4x0422": "hac_v3.3",
    "Run9x0503": "fast_v3.4",
    "Run3x0418": "hac_v3.3",
    "Gridr1": "minion_384",
    "Gridr2": "hac_v3.3",
    "Gridr3": "hac_v3.3",
    "Gridr4": "hac_v3.3",
    "P2r5": "hac_v4.2.0",
    "P2r6": "hac_v4.2.0",
    "P2r7": "hac_v4.2.0",
    "P2r8a": "hac_v4.3.0",
    "P2r8d": "hac_v4.3.0",
    "Gridr5": "hac_v3.3",
    "P2r8": "hac_v4.3.0",
    "P2r8b": "hac_v4.3.0",
    "P2r8c": "hac_v4.3.0",
}

df['group_id'] = df['sample_id'].map(run_basecaller_map)
df.head()

   sample_id                                          file_path     group_id
0  Run4x0314  /nfs/turbo/umms-indikar/shared/projects/HSC/da...  fast_v4.2.0
1  Run3x0314  /nfs/turbo/umms-indikar/shared/projects/HSC/da...  fast_v4.2.0
2  Run1x0312  /nfs/turbo/umms-indikar/shared/projects/HSC/da...  fast_v4.2.0
3  Run6x0426  /nfs/turbo/umms-indikar/shared/projects/HSC/da...     hac_v3.3
4  Run1x0415  /nfs/turbo/umms-indikar/shared/projects/HSC/da...     hac_v3.3

In [11]:
df = df.sort_values(by=['group_id', 'sample_id'])
df

    sample_id                                          file_path     group_id
11  Run8x0426  /nfs/turbo/umms-indikar/shared/projects/HSC/da...    fast_v3.4
13  Run9x0503  /nfs/turbo/umms-indikar/shared/projects/HSC/da...    fast_v3.4
2   Run1x0312  /nfs/turbo/umms-indikar/shared/projects/HSC/da...  fast_v4.2.0
8   Run2x0313  /nfs/turbo/umms-indikar/shared/projects/HSC/da...  fast_v4.2.0
1   Run3x0314  /nfs/turbo/umms-indikar/shared/projects/HSC/da...  fast_v4.2.0
0   Run4x0314  /nfs/turbo/umms-indikar/shared/projects/HSC/da...  fast_v4.2.0
5   Run5x0314  /nfs/turbo/umms-indikar/shared/projects/HSC/da...  fast_v4.2.0
6   Run6x0314  /nfs/turbo/umms-indikar/shared/projects/HSC/da...  fast_v4.2.0
16     Gridr2  /nfs/turbo/umms-indikar/shared/projects/HSC/da...     hac_v3.3
17     Gridr3  /nfs/turbo/umms-indikar/shared/projects/HSC/da...     hac_v3.3
18     Gridr4  /nfs/turbo/umms-indikar/shared/projects/HSC/da...     hac_v3.3
24     Gridr5  /nfs/turbo/umms-indikar/shared/projects/HSC/da...     hac_v3.3
4   Run1x0415  /nfs/turbo/umms-indikar/shared/projects/HSC/da...     hac_v3.3
10  Run2x0416  /nfs/turbo/umms-indikar/shared/projects/HSC/da...     hac_v3.3
14  Run3x0418  /nfs/turbo/umms-indikar/shared/projects/HSC/da...     hac_v3.3
12  Run4x0422  /nfs/turbo/umms-indikar/shared/projects/HSC/da...     hac_v3.3
3   Run6x0426  /nfs/turbo/umms-indikar/shared/projects/HSC/da...     hac_v3.3
7   Run7x0426  /nfs/turbo/umms-indikar/shared/projects/HSC/da...     hac_v3.3
19       P2r5  /nfs/turbo/umms-indikar/shared/projects/HSC/da...   hac_v4.2.0
20       P2r6  /nfs/turbo/umms-indikar/shared/projects/HSC/da...   hac_v4.2.0
21       P2r7  /nfs/turbo/umms-indikar/shared/projects/HSC/da...   hac_v4.2.0
9   Run7x0315  /nfs/turbo/umms-indikar/shared/projects/HSC/da...   hac_v4.2.0
25       P2r8  /nfs/turbo/umms-indikar/shared/projects/HSC/da...   hac_v4.3.0
22      P2r8a  /nfs/turbo/umms-indikar/shared/projects/HSC/da...   hac_v4.3.0
26      P2r8b  /nfs/turbo/umms-indikar/shared/projects/HSC/da...   hac_v4.3.0
27      P2r8c  /nfs/turbo/umms-indikar/shared/projects/HSC/da...   hac_v4.3.0
23      P2r8d  /nfs/turbo/umms-indikar/shared/projects/HSC/da...   hac_v4.3.0
15     Gridr1  /nfs/turbo/umms-indikar/shared/projects/HSC/da...   minion_384

In [14]:
output_path = "../../scrna_processing/grouped_fastq_paths.txt"
df = df[['sample_id', 'group_id', 'file_path']]
df.to_csv(output_path, index=False)
df.head()

    sample_id     group_id                                          file_path
11  Run8x0426    fast_v3.4  /nfs/turbo/umms-indikar/shared/projects/HSC/da...
13  Run9x0503    fast_v3.4  /nfs/turbo/umms-indikar/shared/projects/HSC/da...
2   Run1x0312  fast_v4.2.0  /nfs/turbo/umms-indikar/shared/projects/HSC/da...
8   Run2x0313  fast_v4.2.0  /nfs/turbo/umms-indikar/shared/projects/HSC/da...
1   Run3x0314  fast_v4.2.0  /nfs/turbo/umms-indikar/shared/projects/HSC/da...