In [1]:
import json
import pandas as pd
import sys
import glob
import os

In [4]:
dpath = "/nfs/turbo/umms-indikar/shared/projects/HSC/pipeline_outputs/"

file_list = glob.glob(f"{dpath}*/*/*.config*")
file_list

['/nfs/turbo/umms-indikar/shared/projects/HSC/pipeline_outputs/cc_fibroblast_full/scfib/scfib.config_stats.json',
 '/nfs/turbo/umms-indikar/shared/projects/HSC/pipeline_outputs/hsc_epi2me_full/hac_v3/hac_v3.config_stats.json',
 '/nfs/turbo/umms-indikar/shared/projects/HSC/pipeline_outputs/hsc_epi2me_full/fast_v4.2/fast_v4.2.config_stats.json',
 '/nfs/turbo/umms-indikar/shared/projects/HSC/pipeline_outputs/hsc_epi2me_full/fast_v3/fast_v3.config_stats.json',
 '/nfs/turbo/umms-indikar/shared/projects/HSC/pipeline_outputs/hsc_epi2me_full/minion_384/minion_384.config_stats.json',
 '/nfs/turbo/umms-indikar/shared/projects/HSC/pipeline_outputs/hsc_epi2me_full/hac_v4.3/hac_v4.3.config_stats.json',
 '/nfs/turbo/umms-indikar/shared/projects/HSC/pipeline_outputs/hsc_epi2me_full/hac_v4.2/hac_v4.2.config_stats.json']

In [10]:
result = []

for f in file_list:
    basename = os.path.basename(f)
    df = pd.read_json(f, orient='index').reset_index()
    df.columns = ['stat', 'value']
    df['basename'] = basename
    result.append(df)

result = pd.concat(result)
result

               stat      value                    basename
0          subreads  182431966     scfib.config_stats.json
1       full_length  163541870     scfib.config_stats.json
2          stranded  175445102     scfib.config_stats.json
3              plus   24436220     scfib.config_stats.json
4             minus  151008882     scfib.config_stats.json
..              ...        ...                         ...
7   single_adapter2    4910127  hac_v4.2.config_stats.json
8       no_adapters    1873464  hac_v4.2.config_stats.json
9   single_adapter1    4358493  hac_v4.2.config_stats.json
10            other    1789902  hac_v4.2.config_stats.json
11  double_adapter1     296857  hac_v4.2.config_stats.json

[84 rows x 3 columns]

In [11]:
result[result['stat'] == 'full_length']

          stat      value                      basename
1  full_length  163541870       scfib.config_stats.json
1  full_length   47478161      hac_v3.config_stats.json
1  full_length     795984   fast_v4.2.config_stats.json
1  full_length     761112     fast_v3.config_stats.json
1  full_length   13231753  minion_384.config_stats.json
1  full_length   13689198    hac_v4.3.config_stats.json
1  full_length   84667565    hac_v4.2.config_stats.json

In [12]:
result[result['stat'] == 'full_length']['value'].sum()

324165643